use squawk_syntax::{
    Parse, SourceFile,
    ast::{self, AstNode},
};

use crate::{Linter, Rule, Violation};

pub(crate) fn custom_require_id(ctx: &mut Linter, parse: &Parse<SourceFile>) {
    for stmt in parse.tree().stmts() {
        if let ast::Stmt::CreateTable(create_table) = stmt {
            check_create_table(ctx, create_table);
        }
    }
}

fn check_create_table(ctx: &mut Linter, create_table: ast::CreateTable) {
    let columns = create_table
        .table_arg_list()
        .into_iter()
        .flat_map(|args| args.args())
        .filter_map(|arg| match arg {
            ast::TableArg::Column(column) => Some(column),
            _ => None,
        })
        .collect::<Vec<_>>();

    let Some(column) = columns.iter().find(|column| {
        column
            .name()
            .is_some_and(|column_name| column_name.text() == "id")
    }) else {
        ctx.report(
            Violation::for_node(
                Rule::CustomRequireId,
                "Table is missing required `id` column.".to_string(),
                create_table.syntax(),
            )
            .help(format!("Add `{}`.", expected_column_definition())),
        );
        return;
    };

    if !is_bigint(column.ty().as_ref()) || !has_identity(column) || !has_primary_key(column) {
        ctx.report(Violation::for_node(
            Rule::CustomRequireId,
            "`id` must be `BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`.".to_string(),
            column.syntax(),
        ));
    }
}

fn expected_column_definition() -> &'static str {
    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
}

fn is_bigint(ty: Option<&ast::Type>) -> bool {
    match ty {
        Some(ast::Type::PathType(path_type)) => path_type
            .path()
            .and_then(|path| path.segment())
            .and_then(|segment| segment.name_ref())
            .is_some_and(|name| name.text().eq_ignore_ascii_case("bigint")),
        _ => false,
    }
}

fn has_identity(column: &ast::Column) -> bool {
    compact_text(column.syntax())
        .to_ascii_lowercase()
        .contains("generatedbydefaultasidentity")
}

fn has_primary_key(column: &ast::Column) -> bool {
    column
        .constraints()
        .any(|constraint| matches!(constraint, ast::ColumnConstraint::PrimaryKeyConstraint(_)))
}

fn compact_text(syntax: &squawk_syntax::SyntaxNode) -> String {
    syntax
        .descendants_with_tokens()
        .filter_map(|element| element.into_token())
        .filter(|token| !token.kind().is_trivia())
        .map(|token| token.text().to_string())
        .collect::<Vec<_>>()
        .join("")
}

#[cfg(test)]
mod test {
    use insta::assert_snapshot;

    use crate::{
        Rule,
        test_utils::{lint_errors, lint_ok},
    };

    #[test]
    fn err_missing_field() {
        let sql = r#"
CREATE TABLE my_table (
  name TEXT
);
"#;
        assert_snapshot!(lint_errors(sql, Rule::CustomRequireId));
    }

    #[test]
    fn err_wrong_type() {
        let sql = r#"
CREATE TABLE my_table (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
"#;
        assert_snapshot!(lint_errors(sql, Rule::CustomRequireId));
    }

    #[test]
    fn err_not_generated() {
        let sql = r#"
CREATE TABLE my_table (
  id BIGINT PRIMARY KEY,
  name TEXT
);
"#;
        assert_snapshot!(lint_errors(sql, Rule::CustomRequireId));
    }

    #[test]
    fn err_not_primary_key() {
        let sql = r#"
CREATE TABLE my_table (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name TEXT
);
"#;
        assert_snapshot!(lint_errors(sql, Rule::CustomRequireId));
    }

    #[test]
    fn ok() {
        let sql = r#"
CREATE TABLE my_table (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
"#;
        lint_ok(sql, Rule::CustomRequireId);
    }
}
